exercise_muscles = [
    { exercise_id:  1, muscle_id: 3 },
    { exercise_id:  1, muscle_id: 4 },
    { exercise_id:  1, muscle_id: 5 },
    { exercise_id:  1, muscle_id: 12, primary: true },
    { exercise_id:  1, muscle_id: 6 },
    { exercise_id:  2, muscle_id: 3 },
    { exercise_id:  2, muscle_id: 4 },
    { exercise_id:  2, muscle_id: 5 },
    { exercise_id:  2, muscle_id: 12, primary: true },
    { exercise_id:  2, muscle_id: 6 },
    { exercise_id:  3, muscle_id: 3 },
    { exercise_id:  3, muscle_id: 4 },
    { exercise_id:  3, muscle_id: 5 },
    { exercise_id:  3, muscle_id: 12, primary: true },
    { exercise_id:  3, muscle_id: 6 },
    { exercise_id:  4, muscle_id: 3 },
    { exercise_id:  4, muscle_id: 4 },
    { exercise_id:  4, muscle_id: 5 },
    { exercise_id:  4, muscle_id: 12, primary: true },
    { exercise_id:  5, muscle_id: 3 },
    { exercise_id:  5, muscle_id: 4 },
    { exercise_id:  5, muscle_id: 5 },
    { exercise_id:  5, muscle_id: 12, primary: true },
    { exercise_id:  5, muscle_id: 6 },
    { exercise_id:  6, muscle_id: 3 },
    { exercise_id:  6, muscle_id: 4 },
    { exercise_id:  6, muscle_id: 5 },
    { exercise_id:  6, muscle_id: 12, primary: true },
    { exercise_id:  7, muscle_id: 3 },
    { exercise_id:  7, muscle_id: 4 },
    { exercise_id:  7, muscle_id: 5 },
    { exercise_id:  7, muscle_id: 12, primary: true },
    { exercise_id:  8, muscle_id: 3 },
    { exercise_id:  8, muscle_id: 4 },
    { exercise_id:  8, muscle_id: 5 },
    { exercise_id:  8, muscle_id: 12, primary: true },
    { exercise_id:  8, muscle_id: 6 },
    { exercise_id:  8, muscle_id: 20 },
    { exercise_id:  9, muscle_id: 3 },
    { exercise_id:  9, muscle_id: 4 },
    { exercise_id:  9, muscle_id: 5 },
    { exercise_id:  9, muscle_id: 12, primary: true },
    { exercise_id:  9, muscle_id: 6 },
    { exercise_id:  9, muscle_id: 20 },
    { exercise_id:  9, muscle_id: 13 },
    { exercise_id:  10, muscle_id: 3 },
    { exercise_id:  10, muscle_id: 4 },
    { exercise_id:  10, muscle_id: 5 },
    { exercise_id:  10, muscle_id: 12, primary: true },
    { exercise_id:  10, muscle_id: 6 },
    { exercise_id:  10, muscle_id: 11 },
    { exercise_id:  10, muscle_id: 22 },
    { exercise_id:  10, muscle_id: 13 },
    { exercise_id:  10, muscle_id: 17 },
    { exercise_id:  10, muscle_id: 16 },
    { exercise_id:  11, muscle_id: 3 },
    { exercise_id:  11, muscle_id: 4 },
    { exercise_id:  11, muscle_id: 5 },
    { exercise_id:  11, muscle_id: 12, primary: true },
    { exercise_id:  11, muscle_id: 20 },
    { exercise_id:  11, muscle_id: 6 },
    { exercise_id:  11, muscle_id: 22 },
    { exercise_id:  12, muscle_id: 3 },
    { exercise_id:  12, muscle_id: 4 },
    { exercise_id:  12, muscle_id: 5 },
    { exercise_id:  12, muscle_id: 12, primary: true },
    { exercise_id:  12, muscle_id: 20 },
    { exercise_id:  12, muscle_id: 6 },
    { exercise_id:  13, muscle_id: 12 },
    { exercise_id:  13, muscle_id: 6, primary: true },
    { exercise_id:  14, muscle_id: 3 },
    { exercise_id:  14, muscle_id: 4 },
    { exercise_id:  14, muscle_id: 5 },
    { exercise_id:  14, muscle_id: 12, primary: true },
    { exercise_id:  14, muscle_id: 6 },
    { exercise_id:  15, muscle_id: 3 },
    { exercise_id:  15, muscle_id: 4 },
    { exercise_id:  15, muscle_id: 5 },
    { exercise_id:  15, muscle_id: 12, primary: true },
    { exercise_id:  15, muscle_id: 6 },
    { exercise_id:  16, muscle_id: 12 },
    { exercise_id:  16, muscle_id: 3 },
    { exercise_id:  16, muscle_id: 4 },
    { exercise_id:  16, muscle_id: 5 },
    { exercise_id:  16, muscle_id: 6, primary: true },
    { exercise_id:  17, muscle_id: 3 },
    { exercise_id:  17, muscle_id: 4 },
    { exercise_id:  17, muscle_id: 5 },
    { exercise_id:  17, muscle_id: 12, primary: true },
    { exercise_id:  17, muscle_id: 6 },
    { exercise_id:  18, muscle_id: 3 },
    { exercise_id:  18, muscle_id: 4 },
    { exercise_id:  18, muscle_id: 5 },
    { exercise_id:  18, muscle_id: 12, primary: true },
    { exercise_id:  18, muscle_id: 6 },
    { exercise_id:  18, muscle_id: 11 },
    { exercise_id:  19, muscle_id: 3 },
    { exercise_id:  19, muscle_id: 4 },
    { exercise_id:  19, muscle_id: 5 },
    { exercise_id:  19, muscle_id: 6 },
    { exercise_id:  19, muscle_id: 12, primary: true },
    { exercise_id:  20, muscle_id: 12, primary: true },
    { exercise_id:  20, muscle_id: 20 },
    { exercise_id:  20, muscle_id: 6 },
    { exercise_id:  20, muscle_id: 22 },
    { exercise_id:  21, muscle_id: 3 },
    { exercise_id:  21, muscle_id: 4 },
    { exercise_id:  21, muscle_id: 5 },
    { exercise_id:  21, muscle_id: 12, primary: true },
    { exercise_id:  22, muscle_id: 6, primary: true },
    { exercise_id:  22, muscle_id: 8 },
    { exercise_id:  22, muscle_id: 9 },
    { exercise_id:  23, muscle_id: 3, primary: true },
    { exercise_id:  23, muscle_id: 4, primary: true },
    { exercise_id:  23, muscle_id: 5, primary: true },
    { exercise_id:  23, muscle_id: 6 },
    { exercise_id:  24, muscle_id: 12, primary: true },
    { exercise_id:  24, muscle_id: 6 },
    { exercise_id:  24, muscle_id: 13 },
    { exercise_id:  24, muscle_id: 17 },
    { exercise_id:  24, muscle_id: 18 },
    { exercise_id:  25, muscle_id: 3 },
    { exercise_id:  25, muscle_id: 4 },
    { exercise_id:  25, muscle_id: 5 },
    { exercise_id:  25, muscle_id: 12 },
    { exercise_id:  25, muscle_id: 11, primary: true },
    { exercise_id:  25, muscle_id: 6 },
    { exercise_id:  26, muscle_id: 3 },
    { exercise_id:  26, muscle_id: 4 },
    { exercise_id:  26, muscle_id: 5 },
    { exercise_id:  26, muscle_id: 12, primary: true },
    { exercise_id:  26, muscle_id: 6 },
    { exercise_id:  27, muscle_id: 3 },
    { exercise_id:  27, muscle_id: 4 },
    { exercise_id:  27, muscle_id: 5 },
    { exercise_id:  27, muscle_id: 12, primary: true },
    { exercise_id:  27, muscle_id: 6 },
    { exercise_id:  28, muscle_id: 3 },
    { exercise_id:  28, muscle_id: 4 },
    { exercise_id:  28, muscle_id: 5 },
    { exercise_id:  28, muscle_id: 12, primary: true },
    { exercise_id:  28, muscle_id: 6 },
    { exercise_id:  29, muscle_id: 3 },
    { exercise_id:  29, muscle_id: 4 },
    { exercise_id:  29, muscle_id: 5 },
    { exercise_id:  29, muscle_id: 12, primary: true },
    { exercise_id:  30, muscle_id: 12, primary: true },
    { exercise_id:  30, muscle_id: 6 },
    { exercise_id:  31, muscle_id: 6, primary: true },
    { exercise_id:  32, muscle_id: 6, primary: true },
    { exercise_id:  33, muscle_id: 3 },
    { exercise_id:  33, muscle_id: 4 },
    { exercise_id:  33, muscle_id: 5 },
    { exercise_id:  33, muscle_id: 12, primary: true },
    { exercise_id:  33, muscle_id: 6 },
    { exercise_id:  34, muscle_id: 12, primary: true },
    { exercise_id:  34, muscle_id: 6 },
    { exercise_id:  35, muscle_id: 6, primary: true },
    { exercise_id:  36, muscle_id: 6, primary: true },
    { exercise_id:  37, muscle_id: 6, primary: true },
    { exercise_id:  38, muscle_id: 6, primary: true },
    { exercise_id:  39, muscle_id: 6, primary: true },
    { exercise_id:  40, muscle_id: 6, primary: true },
    { exercise_id:  41, muscle_id: 6, primary: true },
    { exercise_id:  42, muscle_id: 8, primary: true },
    { exercise_id:  42, muscle_id: 9 },
    { exercise_id:  43, muscle_id: 6, primary: true },
    { exercise_id:  44, muscle_id: 3, primary: true },
    { exercise_id:  44, muscle_id: 4, primary: true },
    { exercise_id:  44, muscle_id: 5, primary: true },
    { exercise_id:  44, muscle_id: 6 },
    { exercise_id:  45, muscle_id: 3 },
    { exercise_id:  45, muscle_id: 4, primary: true },
    { exercise_id:  45, muscle_id: 5 },
    { exercise_id:  46, muscle_id: 3, primary: true },
    { exercise_id:  46, muscle_id: 4 },
    { exercise_id:  46, muscle_id: 5 },
    { exercise_id:  47, muscle_id: 3 },
    { exercise_id:  47, muscle_id: 4, primary: true },
    { exercise_id:  47, muscle_id: 5 },
    { exercise_id:  48, muscle_id: 10 },
    { exercise_id:  48, muscle_id: 3, primary: true },
    { exercise_id:  48, muscle_id: 4, primary: true },
    { exercise_id:  48, muscle_id: 5, primary: true },
    { exercise_id:  48, muscle_id: 7 },
    { exercise_id:  48, muscle_id: 6 },
    { exercise_id:  49, muscle_id: 20 },
    { exercise_id:  49, muscle_id: 8 },
    { exercise_id:  49, muscle_id: 9 },
    { exercise_id:  49, muscle_id: 2 },
    { exercise_id:  49, muscle_id: 23 },
    { exercise_id:  49, muscle_id: 16 },
    { exercise_id:  49, muscle_id: 22 },
    { exercise_id:  49, muscle_id: 13 },
    { exercise_id:  49, muscle_id: 15 },
    { exercise_id:  49, muscle_id: 17 },
    { exercise_id:  49, muscle_id: 18 },
    { exercise_id:  50, muscle_id: 1 },
    { exercise_id:  50, muscle_id: 10 },
    { exercise_id:  50, muscle_id: 3 },
    { exercise_id:  50, muscle_id: 4 },
    { exercise_id:  50, muscle_id: 5 },
    { exercise_id:  50, muscle_id: 7 },
    { exercise_id:  50, muscle_id: 8 },
    { exercise_id:  50, muscle_id: 9 },
    { exercise_id:  50, muscle_id: 16, primary: true },
    { exercise_id:  50, muscle_id: 6 },
    { exercise_id:  50, muscle_id: 11 },
    { exercise_id:  50, muscle_id: 22 },
    { exercise_id:  50, muscle_id: 13 },
    { exercise_id:  50, muscle_id: 15 },
    { exercise_id:  50, muscle_id: 17 },
    { exercise_id:  50, muscle_id: 14 },
    { exercise_id:  50, muscle_id: 18 },
    { exercise_id:  51, muscle_id: 3 },
    { exercise_id:  51, muscle_id: 4, primary: true },
    { exercise_id:  51, muscle_id: 5 },
    { exercise_id:  52, muscle_id: 3, primary: true },
    { exercise_id:  52, muscle_id: 4 },
    { exercise_id:  52, muscle_id: 5 },
    { exercise_id:  53, muscle_id: 3 },
    { exercise_id:  53, muscle_id: 4 },
    { exercise_id:  53, muscle_id: 5, primary: true },
    { exercise_id:  54, muscle_id: 3 },
    { exercise_id:  54, muscle_id: 4 },
    { exercise_id:  54, muscle_id: 5, primary: true },
    { exercise_id:  54, muscle_id: 10, primary: true },
    { exercise_id:  54, muscle_id: 8 },
    { exercise_id:  54, muscle_id: 9 },
    { exercise_id:  55, muscle_id: 3 },
    { exercise_id:  55, muscle_id: 4 },
    { exercise_id:  55, muscle_id: 5 },
    { exercise_id:  55, muscle_id: 12, primary: true },
    { exercise_id:  55, muscle_id: 6 },
    { exercise_id:  55, muscle_id: 22 },
    { exercise_id:  55, muscle_id: 11 },
    { exercise_id:  56, muscle_id: 3 },
    { exercise_id:  56, muscle_id: 4 },
    { exercise_id:  56, muscle_id: 5 },
    { exercise_id:  56, muscle_id: 20, primary: true },
    { exercise_id:  56, muscle_id: 22 },
    { exercise_id:  57, muscle_id: 1 },
    { exercise_id:  57, muscle_id: 3 },
    { exercise_id:  57, muscle_id: 4 },
    { exercise_id:  57, muscle_id: 5 },
    { exercise_id:  57, muscle_id: 20, primary: true },
    { exercise_id:  57, muscle_id: 16 },
    { exercise_id:  57, muscle_id: 22 },
    { exercise_id:  57, muscle_id: 13 },
    { exercise_id:  57, muscle_id: 17 },
    { exercise_id:  57, muscle_id: 14 },
    { exercise_id:  58, muscle_id: 3, primary: true },
    { exercise_id:  58, muscle_id: 4, primary: true },
    { exercise_id:  58, muscle_id: 5, primary: true },
    { exercise_id:  58, muscle_id: 6 },
    { exercise_id:  59, muscle_id: 20 },
    { exercise_id:  59, muscle_id: 21 },
    { exercise_id:  59, muscle_id: 16 },
    { exercise_id:  59, muscle_id: 22 },
    { exercise_id:  59, muscle_id: 13 },
    { exercise_id:  59, muscle_id: 15 },
    { exercise_id:  59, muscle_id: 17, primary: true },
    { exercise_id:  59, muscle_id: 14, primary: true },
    { exercise_id:  60, muscle_id: 10, primary: true },
    { exercise_id:  60, muscle_id: 3 },
    { exercise_id:  60, muscle_id: 4 },
    { exercise_id:  60, muscle_id: 5 },
    { exercise_id:  60, muscle_id: 16 },
    { exercise_id:  60, muscle_id: 13 },
    { exercise_id:  60, muscle_id: 17 },
    { exercise_id:  60, muscle_id: 14 },
    { exercise_id:  60, muscle_id: 18 },
    { exercise_id:  61, muscle_id: 20 },
    { exercise_id:  61, muscle_id: 8 },
    { exercise_id:  61, muscle_id: 9 },
    { exercise_id:  61, muscle_id: 2 },
    { exercise_id:  61, muscle_id: 23 },
    { exercise_id:  61, muscle_id: 16 },
    { exercise_id:  61, muscle_id: 22 },
    { exercise_id:  61, muscle_id: 13, primary: true },
    { exercise_id:  61, muscle_id: 15 },
    { exercise_id:  61, muscle_id: 17 },
    { exercise_id:  61, muscle_id: 14 },
    { exercise_id:  61, muscle_id: 18 },
    { exercise_id:  62, muscle_id: 3, primary: true },
    { exercise_id:  62, muscle_id: 4, primary: true },
    { exercise_id:  62, muscle_id: 5, primary: true },
    { exercise_id:  62, muscle_id: 20 },
    { exercise_id:  62, muscle_id: 8 },
    { exercise_id:  62, muscle_id: 9 },
    { exercise_id:  62, muscle_id: 16 },
    { exercise_id:  63, muscle_id: 3 },
    { exercise_id:  63, muscle_id: 4 },
    { exercise_id:  63, muscle_id: 5, primary: true },
    { exercise_id:  64, muscle_id: 3 },
    { exercise_id:  64, muscle_id: 4 },
    { exercise_id:  64, muscle_id: 5, primary: true },
    { exercise_id:  65, muscle_id: 10, primary: true },
    { exercise_id:  65, muscle_id: 8 },
    { exercise_id:  65, muscle_id: 9 },
    { exercise_id:  65, muscle_id: 16 },
    { exercise_id:  65, muscle_id: 11 },
    { exercise_id:  65, muscle_id: 22 },
    { exercise_id:  65, muscle_id: 13 },
    { exercise_id:  65, muscle_id: 15 },
    { exercise_id:  65, muscle_id: 17, primary: true },
    { exercise_id:  65, muscle_id: 14, primary: true },
    { exercise_id:  65, muscle_id: 18 },
    { exercise_id:  65, muscle_id: 3 },
    { exercise_id:  65, muscle_id: 4 },
    { exercise_id:  65, muscle_id: 5 },
    { exercise_id:  66, muscle_id: 10 },
    { exercise_id:  66, muscle_id: 3, primary: true },
    { exercise_id:  66, muscle_id: 4, primary: true },
    { exercise_id:  66, muscle_id: 5, primary: true },
    { exercise_id:  66, muscle_id: 16 },
    { exercise_id:  66, muscle_id: 22 },
    { exercise_id:  66, muscle_id: 13 },
    { exercise_id:  66, muscle_id: 18 },
    { exercise_id:  66, muscle_id: 8 },
    { exercise_id:  66, muscle_id: 9 },
    { exercise_id:  67, muscle_id: 10 },
    { exercise_id:  67, muscle_id: 3 },
    { exercise_id:  67, muscle_id: 4, primary: true },
    { exercise_id:  67, muscle_id: 5, primary: true },
    { exercise_id:  67, muscle_id: 11 },
    { exercise_id:  68, muscle_id: 3, primary: true },
    { exercise_id:  68, muscle_id: 4, primary: true },
    { exercise_id:  68, muscle_id: 5, primary: true },
    { exercise_id:  68, muscle_id: 12 },
    { exercise_id:  68, muscle_id: 11 },
    { exercise_id:  68, muscle_id: 6 },
    { exercise_id:  69, muscle_id: 3 },
    { exercise_id:  69, muscle_id: 4 },
    { exercise_id:  69, muscle_id: 5, primary: true },
    { exercise_id:  69, muscle_id: 11 },
    { exercise_id:  70, muscle_id: 3, primary: true },
    { exercise_id:  70, muscle_id: 4, primary: true },
    { exercise_id:  70, muscle_id: 5, primary: true },
    { exercise_id:  70, muscle_id: 6 },
    { exercise_id:  71, muscle_id: 3, primary: true },
    { exercise_id:  71, muscle_id: 4, primary: true },
    { exercise_id:  71, muscle_id: 5, primary: true },
    { exercise_id:  71, muscle_id: 12 },
    { exercise_id:  71, muscle_id: 6 },
    { exercise_id:  72, muscle_id: 3, primary: true },
    { exercise_id:  72, muscle_id: 4, primary: true },
    { exercise_id:  72, muscle_id: 5, primary: true },
    { exercise_id:  72, muscle_id: 6 },
    { exercise_id:  73, muscle_id: 3, primary: true },
    { exercise_id:  73, muscle_id: 4, primary: true },
    { exercise_id:  73, muscle_id: 5, primary: true },
    { exercise_id:  73, muscle_id: 6 },
    { exercise_id:  74, muscle_id: 3, primary: true },
    { exercise_id:  74, muscle_id: 4, primary: true },
    { exercise_id:  74, muscle_id: 5, primary: true },
    { exercise_id:  74, muscle_id: 6 },
    { exercise_id:  75, muscle_id: 3, primary: true },
    { exercise_id:  75, muscle_id: 4, primary: true },
    { exercise_id:  75, muscle_id: 5, primary: true },
    { exercise_id:  75, muscle_id: 6 },
    { exercise_id:  76, muscle_id: 3 },
    { exercise_id:  76, muscle_id: 4, primary: true },
    { exercise_id:  76, muscle_id: 5, primary: true },
    { exercise_id:  76, muscle_id: 6 },
    { exercise_id:  77, muscle_id: 3, primary: true },
    { exercise_id:  77, muscle_id: 4, primary: true },
    { exercise_id:  77, muscle_id: 5, primary: true },
    { exercise_id:  77, muscle_id: 6 },
    { exercise_id:  78, muscle_id: 3, primary: true },
    { exercise_id:  78, muscle_id: 4, primary: true },
    { exercise_id:  78, muscle_id: 5, primary: true },
    { exercise_id:  78, muscle_id: 6 },
    { exercise_id:  79, muscle_id: 3 },
    { exercise_id:  79, muscle_id: 4, primary: true },
    { exercise_id:  79, muscle_id: 5, primary: true },
    { exercise_id:  79, muscle_id: 6 },
    { exercise_id:  80, muscle_id: 3, primary: true },
    { exercise_id:  80, muscle_id: 4, primary: true },
    { exercise_id:  80, muscle_id: 5, primary: true },
    { exercise_id:  80, muscle_id: 10 },
    { exercise_id:  81, muscle_id: 10 },
    { exercise_id:  81, muscle_id: 3, primary: true },
    { exercise_id:  81, muscle_id: 4, primary: true },
    { exercise_id:  81, muscle_id: 5, primary: true },
    { exercise_id:  81, muscle_id: 7 },
    { exercise_id:  82, muscle_id: 10 },
    { exercise_id:  82, muscle_id: 3, primary: true },
    { exercise_id:  82, muscle_id: 4, primary: true },
    { exercise_id:  82, muscle_id: 5, primary: true },
    { exercise_id:  82, muscle_id: 7 },
    { exercise_id:  83, muscle_id: 3 },
    { exercise_id:  83, muscle_id: 4, primary: true },
    { exercise_id:  83, muscle_id: 5 },
    { exercise_id:  84, muscle_id: 3 },
    { exercise_id:  84, muscle_id: 4, primary: true },
    { exercise_id:  84, muscle_id: 5 },
    { exercise_id:  85, muscle_id: 3 },
    { exercise_id:  85, muscle_id: 4, primary: true },
    { exercise_id:  85, muscle_id: 5, primary: true },
    { exercise_id:  86, muscle_id: 3, primary: true },
    { exercise_id:  86, muscle_id: 4, primary: true },
    { exercise_id:  86, muscle_id: 5 },
    { exercise_id:  87, muscle_id: 3, primary: true },
    { exercise_id:  87, muscle_id: 4, primary: true },
    { exercise_id:  87, muscle_id: 5 },
    { exercise_id:  88, muscle_id: 3, primary: true },
    { exercise_id:  88, muscle_id: 4, primary: true },
    { exercise_id:  88, muscle_id: 5, primary: true },
    { exercise_id:  88, muscle_id: 7 },
    { exercise_id:  89, muscle_id: 3 },
    { exercise_id:  89, muscle_id: 4 },
    { exercise_id:  89, muscle_id: 5, primary: true },
    { exercise_id:  90, muscle_id: 10 },
    { exercise_id:  90, muscle_id: 3 },
    { exercise_id:  90, muscle_id: 4 },
    { exercise_id:  90, muscle_id: 5, primary: true },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },
    { exercise_id:  , muscle_id:  },

]