exercise_muscles = [
    { exercise_id: 1, muscle_id: 6 },
    { exercise_id: 2, muscle_id: 6 },
    { exercise_id: 3, muscle_id: 6 },
    { exercise_id: 4, muscle_id: 6 },
    { exercise_id: 5, muscle_id: 6 },
    { exercise_id: 6, muscle_id: 6 },
    { exercise_id: 7, muscle_id: 6 },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },
    { exercise_id: , muscle_id:  },

]