exercise_muscle_groups = [
    { exercise_id: 1, muscle_group_id: 3, primary: true },
    { exercise_id: 1, muscle_group_id: 2, primary: false },
    { exercise_id: 1, muscle_group_id: 1, primary: false },
    { exercise_id: 2, muscle_group_id: 3, primary: true },
    { exercise_id: 2, muscle_group_id: 2, primary: false },
    { exercise_id: 2, muscle_group_id: 1, primary: false },
    { exercise_id: 3, muscle_group_id: 3, primary: true },
    { exercise_id: 3, muscle_group_id: 2, primary: false },
    { exercise_id: 3, muscle_group_id: 1, primary: false },
    { exercise_id: 4, muscle_group_id: 3, primary: true },
    { exercise_id: 4, muscle_group_id: 2, primary: false },
    { exercise_id: 4, muscle_group_id: 1, primary: false },
    { exercise_id: 5, muscle_group_id: 3, primary: true },
    { exercise_id: 5, muscle_group_id: 2, primary: false },
    { exercise_id: 5, muscle_group_id: 1, primary: false },
    { exercise_id: 6, muscle_group_id: 3, primary: true },
    { exercise_id: 6, muscle_group_id: 2, primary: false },
    { exercise_id: 6, muscle_group_id: 1, primary: false },
    { exercise_id: 7, muscle_group_id: 3, primary: true },
    { exercise_id: 7, muscle_group_id: 2, primary: false },
    { exercise_id: 7, muscle_group_id: 1, primary: false },
    { exercise_id: 8, muscle_group_id: 3, primary: true },
    { exercise_id: 8, muscle_group_id: 2, primary: true },
    { exercise_id: 8, muscle_group_id: 6, primary: false },
    { exercise_id: 8, muscle_group_id: 4, primary: false },
    { exercise_id: 8, muscle_group_id: 5, primary: false },
    { exercise_id: 8, muscle_group_id: 1, primary: false },
    { exercise_id: 9, muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },
    { exercise_id: , muscle_group_id: , primary:  },

]